### PR TITLE
Relax Symfony package version constraints

### LINKED ISSUE #236: Not compatible with symfony 4.4
I'm trying to install library and got error:
```
$ composer require youshido/graphql
Using version ^1.7 for youshido/graphql
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "4.4.*"
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for youshido/graphql ^1.7 -> satisfiable by youshido/graphql[v1.7.0].
    - youshido/graphql v1.7.0 requires symfony/property-access ^2.8 -> no matching package found.

```
But version 1.6 installed successful. Something wrong with `symfony/property-access`?

### PR DESCRIPTION
**Pull request by Jalle19**
Fixes #236

### CODE REVIEW

**Comment by Jalle19** [comment]
@perf2k2 can you try `composer require youshido/graphql:dev-master#00d39f0ddeb74953f520e1d3b22e63a6ef35a0f1`

**Comment by perf2k2** [comment]
@Jalle19 thanks for quick repsonse! 
But composer doesn't want to give up:
```
$ composer require youshido/graphql:dev-master#00d39f0ddeb74953f520e1d3b22e63a6ef35a0f1"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for youshido/graphql dev-master#00d39f0ddeb74953f520e1d3b22e63a6ef35a0f1 -> satisfiable by youshido/graphql[dev-master].
    - Conclusion: remove symfony/property-access v4.4.2
    - Conclusion: don't install symfony/property-access v4.4.2
    - youshido/graphql dev-master requires symfony/property-access ^2.8 -> satisfiable by symfony/property-access[2.8.x-dev, v2.8.0, v2.8.0-BETA1, v2.8.1, v2.8.10, v2.8.11, v2.8.12, v2.8.13, v2.8.14, v2.8.15, v2.8.16, v2.8.17, v2.8.18, v2.8.19, v2.8.2, v2.8.20, v2.8.21, v2.8.22, v2.8.23, v2.8.24, v2.8.25, v2.8.26, v2.8.27, v2.8.28, v2.8.29, v2.8.3, v2.8.30, v2.8.31, v2.8.32, v2.8.33, v2.8.34, v2.8.35, v2.8.36, v2.8.37, v2.8.38, v2.8.39, v2.8.4, v2.8.40, v2.8.41, v2.8.42, v2.8.43, v2.8.44, v2.8.45, v2.8.46, v2.8.47, v2.8.48, v2.8.49, v2.8.5, v2.8.50, v2.8.52, v2.8.6, v2.8.7, v2.8.8, v2.8.9].
    - Can only install one of: symfony/property-access[2.8.x-dev, v4.4.2].
    - Can only install one of: symfony/property-access[v2.8.0, v4.4.2].
    - Can only install one of: symfony/property-access[v2.8.0-BETA1, v4.4.2].
    - Can only install one of: symfony/property-access[v2.8.1, v4.4.2].
    - Can only install one of: symfony/property-access[v2.8.10, v4.4.2].
    - Can only install one of: symfony/property-access[v2.8.11, v4.4.2].
    - Can only install one of: symfony/property-access[v2.8.12, v4.4.2].
    - Can only install one of: symfony/property-access[v2.8.13, v4.4.2].
    - Can only install one of: symfony/property-access[v2.8.14, v4.4.2].
    - Can only install one of: symfony/property-access[v2.8.15, v4.4.2].
    - Can only install one of: symfony/property-access[v2.8.16, v4.4.2].
    - Can only install one of: symfony/property-access[v2.8.17, v4.4.2].
    - Can only install one of: symfony/property-access[v2.8.18, v4.4.2].
    - Can only install one of: symfony/property-access[v2.8.19, v4.4.2].
    - Can only install one of: symfony/property-access[v2.8.2, v4.4.2].
    - Can only install one of: symfony/property-access[v2.8.20, v4.4.2].
    - Can only install one of: symfony/property-access[v2.8.21, v4.4.2].
    - Can only install one of: symfony/property-access[v2.8.22, v4.4.2].
    - Can only install one of: symfony/property-access[v2.8.23, v4.4.2].
    - Can only install one of: symfony/property-access[v2.8.24, v4.4.2].
    - Can only install one of: symfony/property-access[v2.8.25, v4.4.2].
    - Can only install one of: symfony/property-access[v2.8.26, v4.4.2].
    - Can only install one of: symfony/property-access[v2.8.27, v4.4.2].
    - Can only install one of: symfony/property-access[v2.8.28, v4.4.2].
    - Can only install one of: symfony/property-access[v2.8.29, v4.4.2].
    - Can only install one of: symfony/property-access[v2.8.3, v4.4.2].
    - Can only install one of: symfony/property-access[v2.8.30, v4.4.2].
    - Can only install one of: symfony/property-access[v2.8.31, v4.4.2].
    - Can only install one of: symfony/property-access[v2.8.32, v4.4.2].
    - Can only install one of: symfony/property-access[v2.8.33, v4.4.2].
    - Can only install one of: symfony/property-access[v2.8.34, v4.4.2].
    - Can only install one of: symfony/property-access[v2.8.35, v4.4.2].
    - Can only install one of: symfony/property-access[v2.8.36, v4.4.2].
    - Can only install one of: symfony/property-access[v2.8.37, v4.4.2].
    - Can only install one of: symfony/property-access[v2.8.38, v4.4.2].
    - Can only install one of: symfony/property-access[v2.8.39, v4.4.2].
    - Can only install one of: symfony/property-access[v2.8.4, v4.4.2].
    - Can only install one of: symfony/property-access[v2.8.40, v4.4.2].
    - Can only install one of: symfony/property-access[v2.8.41, v4.4.2].
    - Can only install one of: symfony/property-access[v2.8.42, v4.4.2].
    - Can only install one of: symfony/property-access[v2.8.43, v4.4.2].
    - Can only install one of: symfony/property-access[v2.8.44, v4.4.2].
    - Can only install one of: symfony/property-access[v2.8.45, v4.4.2].
    - Can only install one of: symfony/property-access[v2.8.46, v4.4.2].
    - Can only install one of: symfony/property-access[v2.8.47, v4.4.2].
    - Can only install one of: symfony/property-access[v2.8.48, v4.4.2].
    - Can only install one of: symfony/property-access[v2.8.49, v4.4.2].
    - Can only install one of: symfony/property-access[v2.8.5, v4.4.2].
    - Can only install one of: symfony/property-access[v2.8.50, v4.4.2].
    - Can only install one of: symfony/property-access[v2.8.52, v4.4.2].
    - Can only install one of: symfony/property-access[v2.8.6, v4.4.2].
    - Can only install one of: symfony/property-access[v2.8.7, v4.4.2].
    - Can only install one of: symfony/property-access[v2.8.8, v4.4.2].
    - Can only install one of: symfony/property-access[v2.8.9, v4.4.2].
    - Installation request for symfony/property-access (locked at v4.4.2) -> satisfiable by symfony/property-access[v4.4.2].
```

**Comment by Jalle19** [comment]
Can you try with dev-composer-fixea instead of dev-master?

**Comment by perf2k2** [comment]
It works, thanks)

**Comment by Jalle19** [comment]
I tagged this as v1.7.1, but it usually takes some time before it appears on Packagist (see https://packagist.org/packages/youshido/graphql).

@viniychuk if you did something last time to make v1.7.0 appear there, please can you do the same thing again?

**Pull request merged**
