### PR TITLE
Fixed nullable arguments in wrong order to ensure PHP8 runs the code

### LINKED ISSUE #248: Errors when using with PHP 8.0
I noticed that to be using PHP8 with this package, some functions must be updated so that no required parameter is declared after an optional parameter.

I made a PR for this, this is a fix for our project, but I don't see where this could harm the general usage.

### PR DESCRIPTION
**Pull request by florentdestremau**
Fixes #248

### CODE REVIEW

**Review by Jalle19 — APPROVED** [review]

**Comment by florentdestremau** [comment]
@Jalle19 happy to see that you reviewed this PR. What will it take to merge it?

**Comment by Jalle19** [comment]
Not much, it's just that no one has touched this repository in a while so I'm a bit hesitant. Might need to redo the CI setup etc.

**Comment by florentdestremau** [comment]
Well to be honest I consider this repository abandoned, but not enough time to migrate to another solution for GraphQL & Symfony. I plan to try and upgrade it to Symfony 5 as it's the only repository preventing us to do so. I might make another PR based on what is needed on our fork.

**Comment by Jalle19** [comment]
Yeah, it is indeed abandoned. I used to keep it on life support as part of my day job, but since switching jobs I simply haven't had the inclination to do any maintenance.

I'll merge this so you can at least use `dev-master#commit` without having to fork. Feel free to make pull requests if you have patches lying around in your fork!

**Comment by florentdestremau** [comment]
Thanks for the merge ! Yeah this summer I plan to move up to Symfony 5 in our project so I may have to tackle some issues on the repo, and I'll push them here.

**Pull request merged**
